name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    #Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgtest-dev libfmt-dev

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - uses: ZedThree/clang-tidy-review@v0.14.0
      id: review

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
      