name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on:
  pull_request:
      paths:
      - '**.cpp'
      - '**.h'
  push:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ZedThree/clang-tidy-review@v0.14.0
      id: review
      with:
        apt_packages: libgtest-dev, libfmt-dev, liblapack-dev
        config_file: ".clang-tidy"
        exclude: "test/*.cpp"
        cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Upload clang-tidy fixes
      uses: ZedThree/clang-tidy-review/upload@v0.14.0

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
      